INSERT INTO code(label,code,codeType,displayOrder,Remark) values('女','F','gender',1,'性别'),
('男','M','gender',0,'性别'),
('A级','A','customerGrade',0,'客户等级'),
('B级','B','customerGrade',1,'客户等级'),
('代理商','Agent','customerType',0,'客户类型'),
('公立医院','Hosp0','customerType',1,'客户类型'),
('私立医院','Hosp1','customerType',2,'客户类型'),
('体检机构','Body','customerType',3,'客户类型'),
('医检所','MedLab','customerType',4,'客户类型'),
('药店','Pharmacy','customerType',5,'客户类型'),
('电商平台','EBusiness','customerType',6,'客户类型'),
('其它企业','Other','customerType',7,'客户类型'),
('个人','Personal','customerType',8,'客户类型'),
('成功客户','S','customerStatus',0,'客户状态'),
('外部关系介绍','Outer','customerWay',0,'客户获得途径'),
('内部部关系介绍','Inner','customerWay',1,'客户获得途径'),
('拜访','visit','customerWay',2,'客户获得途径'),
('电话','Phone','customerWay',3,'客户获得途径'),
('其它','Other','customerWay',4,'客户获得途径'),

('三级','3H','hospitalGrade',0,'医院等级'),
('三甲','3HA','hospitalGrade',1,'医院等级'),
('二级','2H','hospitalGrade',3,'医院等级'),
('一级','1H','hospitalGrade',4,'医院等级'),
('标志性','SH','hospitalGrade',2,'医院等级'),
('社区','CH','hospitalGrade',5,'医院等级'),
('未分级','H0','hospitalGrade',6,'医院等级'),

('公立','State','hospitalType',0,'医院性质'),
('民营','Partners','hospitalType',1,'医院性质'),
('其它','Other','hospitalType',2,'医院性质'),
('超大型','SL','scale',0,'规模'),
('大型','Large','scale',1,'规模'),
('中大型','ML','scale',2,'规模'),
('中型','MED','scale',3,'规模'),
('小型','SMALL','scale',4,'规模'),
('微型','TINY','scale',5,'规模'),
('私营企业','PE','Comp',0,'企业性质'),
('国有企业','NE','Comp',1,'企业性质'),
('公立医院','NH','Comp',2,'企业性质'),
('民营医院','PH','Comp',3,'企业性质'),
('外资企业','FE','Comp',4,'企业性质');


INSERT INTO code(label,code,codeType,displayOrder,Remark) values
('客户筛选/接洽客户','S0','saleStage', 0,'销售工作进展'),
('代理商签约','S1','saleStage',1,'销售工作进展'),
('科室提单','S2','saleStage',2,'销售工作进展'),
('院内立项','S3','saleStage', 3,'销售工作进展'),
('过会','S4','saleStage',4,'销售工作进展'),
('递交材料','S5','saleStage',5,'销售工作进展'),
('招标/议价','S6','saleStage', 6,'销售工作进展'),
('招标公示','S7','saleStage',7,'销售工作进展'),
('签订采购合同','S8','saleStage',8,'销售工作进展'),
('上收费系统','S9','saleStage', 9,'销售工作进展'),
('临采','S10','saleStage',10,'销售工作进展'),
('医院收样外送','S11','saleStage',10,'销售工作进展');

INSERT INTO code(label,code,codeType,displayOrder,Remark) values


